
#
# (c) 2024 Andreas Geyer-Schulz
#          Meta GA examples.
#

#' Aggregate log files generated by \code{metaGAReporter()}.
#'
#' @description All log files generated by the 
#'              \code{metaGAReporter()} which are present
#'              in the local directory are combined into a single 
#'              vector.
#'
#' @param pattern   Regular expression which matches the files 
#'                  produced by a single run of a meta GA.
#'
#' @return A vector of all solutions tried sorted by decreasing 
#'         average GA performance.
#'
#' @family Reports
#'
#'@importFrom stats sd
#'@export
aggregateMetaResults<-function(pattern)
{
# read all files in local directory
a<-list.files(pattern=pattern)
#a<-list.files()
# cat("pattern:", pattern,"files:\n")
# print(a)
b<-lapply(a, FUN=readRDS)
# extract all fields of the same type.
extractParms<-function(elem) {  return(elem$param)  }
extractGAfit<-function(elem) {  return(elem$GAfit)  }
extractExperiment<-function(elem) {  return(elem$experiment)  }
# append data frames 
append<-function(df1, df2) {return (rbind(df1, df2))}
c<-lapply(b, extractParms)
fit<-lapply(b, extractGAfit)
exp<-lapply(b, extractExperiment)
d<-unique(c)
r<-list()
# cat("length(d)", length(d), "\n")
# construct new list. Keep raw data.
for (i in 1:length(d))
{
# cat("d[[", i, "]]\n") 
# print(d[[i]])
el<-list()
el$param<-d[[i]]
m<-c %in% d[i]
tmp<-unlist(fit[m])
el$GAfitVec<-tmp
el$GAfit<-mean(tmp)
el$GAstd<-sd(tmp)
el$GAobs<-length(tmp)
el$exp<-Reduce(append, exp[m])
r[[i]]<-el
}

s<-sort(unlist(lapply(r, extractGAfit)), decreasing=TRUE, index.return=TRUE)

result<-r[s$ix]
return(result)
}

#' Convert list of all tried GA solutions into a data frame.
#'
#' @param l  List of all solutions tried generated by 
#'           \code{aggregateP5MetaResults()}.
#' @param solution Solution of meta GA.
#'           
#' @return   A data frame with the following columns:
#'           \enumerate{
#'           \item \code{Fit}   Average GA performance of parameters.
#'           \item \code{sigma(Fit)} Standard deviation of \code{Fit}.
#'           \item \code{Obs}   Number of repetitions genetic algorithm
#'                              with a parameter set.
#'           \item \code{popsize} Population size (Meta-GA parameter).
#'           \item \code{generations} Population size (Meta-GA parameter).
#'           \item \code{mutrate} Probability of applying mutation operator.
#'                                  (Meta-GA parameter).
#'           \item \code{bitmutrate} Bit mutation rate.
#'                                  (Meta-GA parameter).
#'           \item \code{crossrate} Probability of applying crossover operator. 
#'                                  (Meta-GA parameter).
#'           } 
#'
#' @export
convertMetaResults<-function(l, solution)
{
# extract all fields of the same type.
extractParms<-function(elem)
{  return(elem$param)  }
extractGAfit<-function(elem)
{  return(elem$GAfit)  }
extractGAstd<-function(elem)
{  return(elem$GAstd)  }
extractGAobs<-function(elem)
{  return(elem$GAobs)  }
# data transformations
tmp<-lapply(l, FUN=extractParms)
df1<-t(data.frame(tmp))
fit<-unlist(lapply(l, FUN=extractGAfit))
std<-unlist(lapply(l, FUN=extractGAstd))
obs<-unlist(lapply(l, FUN=extractGAobs))
df2<-data.frame(fit, std, obs)
result<-cbind(df2, df1)
### Dependency!
cn<-c("Fit", "sigma(Fit)", "Obs")
cn<-c(cn, solution$GAenv$penv$pnames())
row.names(result)<-NULL
names(result)<-cn
return(result)
}

#' Backend processing.
#'
#' @description  Produces several files.
#'
#' @param solution  meta GA solution.
#'
#' @return  A data frame. GA-parameters sorted by decreasing fitness.
#'
#'@export
metaGApostProcessing<-function(solution)
{
# solution
metaGAfns<-metaGAfn(name=solution$GAenv$penv$name(), path="")
saveRDS(solution, file=metaGAfns$solution)
# aggregate experimental data
experiment<-aggregateMetaResults(pattern=metaGAfns$log)
saveRDS(experiment, file=metaGAfns$experiment)
# convert to data frame
details<-convertMetaResults(experiment, solution=solution)
saveRDS(details, file=metaGAfns$details)
return(details)
}
