
#
# (c) 2024 Andreas Geyer-Schulz
#          Meta GA examples.
#

#' Aggregate log files generated by \code{metaGAReporter()}.
#'
#' @description All log files generated by the 
#'              \code{metaGAReporter()} which are present
#'              in the local directory are combined into a single 
#'              vector.
#'
#' @param pattern   Regular expression which matches the files 
#'                  produced by a single run of a meta GA.
#' @param path      Path for log files. Default: \code{""}. 
#'
#' @return A vector of all solutions tried sorted by decreasing 
#'         average GA performance.
#'
#' @family Reports
#'
#'@importFrom stats sd
#'@export
aggregateMetaResults<-function(pattern, path)
{
a<-list.files(path=path, pattern=pattern)
aa<-lapply(a, 
           FUN=function(x, path=path) {paste(path, x, sep="")}, 
           path=path)
b<-lapply(aa, FUN=readRDS)
# extract all fields of the same type.
extractParms<-function(elem) {  return(elem$param)  }
extractGAfit<-function(elem) {  return(elem$GAfit)  }
extractTime<-function(elem) {  return(elem$GAtime)  }
extractExperiment<-function(elem) {  return(elem$experiment)  }
# append data frames 
append<-function(df1, df2) {return (rbind(df1, df2))}
c<-lapply(b, extractParms)
fit<-lapply(b, extractGAfit)
tsec<-lapply(b, extractTime)
exp<-lapply(b, extractExperiment)
d<-unique(c)
r<-list()
# cat("length(d)", length(d), "\n")
# construct new list. Keep raw data.
for (i in 1:length(d))
{
# cat("d[[", i, "]]\n") 
# print(d[[i]])
el<-list()
el$param<-d[[i]]
m<-c %in% d[i] ## index
tmpfit<-unlist(fit[m])
tmptsec<-unlist(tsec[m])
el$GAfitVec<-tmpfit
el$GAtimeVec<-tmptsec
el$GAtime<-mean(tmptsec)
el$GAtimestd<-sd(tmptsec)
el$GAfit<-mean(tmpfit)
el$GAstd<-sd(tmpfit)
el$GAobs<-length(tmpfit)
el$exp<-Reduce(append, exp[m])
r[[i]]<-el
}

s<-sort(unlist(lapply(r, extractGAfit)), decreasing=TRUE, index.return=TRUE)

result<-r[s$ix]
return(result)
}

#' Convert list of all tried GA solutions into a data frame.
#'
#' @param l  List of all solutions tried generated by 
#'           \code{aggregateP5MetaResults()}.
#' @param solution Solution of meta GA.
#'           
#' @return   A data frame with the following columns:
#'           \enumerate{
#'           \item \code{Fit}   Average GA performance of parameters.
#'           \item \code{sigma(Fit)} Standard deviation of \code{Fit}.
#'           \item \code{Obs}   Number of repetitions genetic algorithm
#'                              with a parameter set.
#'           \item \code{popsize} Population size (Meta-GA parameter).
#'           \item \code{generations} Population size (Meta-GA parameter).
#'           \item \code{mutrate} Probability of applying mutation operator.
#'                                  (Meta-GA parameter).
#'           \item \code{bitmutrate} Bit mutation rate.
#'                                  (Meta-GA parameter).
#'           \item \code{crossrate} Probability of applying crossover operator. 
#'                                  (Meta-GA parameter).
#'           } 
#'
#' @export
convertMetaResults<-function(l, solution)
{
# extract all fields of the same type.
extractParms<-function(elem)
{  return(elem$param)  }
extractGAfit<-function(elem)
{  return(elem$GAfit)  }
extractGAstd<-function(elem)
{  return(elem$GAstd)  }
extractGAtime<-function(elem)
{  return(elem$GAtime)  }
extractGAtimestd<-function(elem)
{  return(elem$GAtimestd)  }
extractGAobs<-function(elem)
{  return(elem$GAobs)  }
# data transformations
tmp<-lapply(l, FUN=extractParms)
df1<-t(data.frame(tmp))
fit<-unlist(lapply(l, FUN=extractGAfit))
std<-unlist(lapply(l, FUN=extractGAstd))
sec<-unlist(lapply(l, FUN=extractGAtime))
stdsec<-unlist(lapply(l, FUN=extractGAtimestd))
obs<-unlist(lapply(l, FUN=extractGAobs))
df2<-data.frame(fit, std, sec, stdsec, obs)
result<-cbind(df2, df1)
cn<-c("Fit", "sigma(Fit)", "t", "sigma(t)", "Obs")
cn<-c(cn, solution$GAenv$penv$pnames())
row.names(result)<-NULL
names(result)<-cn
return(result)
}

#' Backend processing.
#'
#' @description  Produce a single file which contains the meta GA experiment 
#'               results. The file name contains \code{"-rMeta-"}.
#'               If no path is specified, the file is written into 
#'               the current directory.
#'
#' @param solution  The Meta GA solution.
#' @param path      Path to file directory. Default: \code{""}.
#'
#' @return A named list with the following elements:
#'         \itemize{
#'         \item \code{$solution}    The meta GA solution. 
#'         \item \code{$experiment}  A list.
#'         \item \code{$details}     A data frame. 
#'         }
#'@export
metaGApostProcessing<-function(solution, path="")
{
# solution
metaGAfns<-metaGAfn(name=solution$GAenv$penv$name(), path=path)
# saveRDS(solution, file=metaGAfns$solution)
# aggregate experimental data
experiment<-aggregateMetaResults(pattern=metaGAfns$logpattern, path=path)
# saveRDS(experiment, file=metaGAfns$experiment)
# convert to data frame
details<-convertMetaResults(experiment, solution=solution)
# saveRDS(details, file=metaGAfns$details)
l<-list()
l$solution<-solution
l$experiment<-experiment
l$details<-details
saveRDS(l, file=metaGAfns$rMeta)
return(l)
}

