
#
# (c) 2024 Andreas Geyer-Schulz
#          Meta GA examples.
#

#' Aggregate files of P5Reporter.
#'
#' @description All files generated by a P5Reporter which are present
#'              in the local directory are combined into a single 
#'              vector.
#'
#' @param pattern   Regular expression which matches the files 
#'                  produced by a single run of a meta GA.
#'
#' @return A vector of all solutions tried sorted by decreasing 
#'         average GA performance.
#'
#' @family Reports
#'
#'@importFrom stats sd
#'@export
aggregateP5MetaResults<-function(pattern)
{
# read all files in local directory
a<-list.files(pattern=pattern)
cat("files:")
print(a)
b<-lapply(a, FUN=readRDS)
# extract all fields of the same type.
extractParms<-function(elem) {  return(elem$param)  }
extractGAfit<-function(elem) {  return(elem$GAfit)  }
extractExperiment<-function(elem) {  return(elem$experiment)  }
# append data frames 
append<-function(df1, df2) {return (rbind(df1, df2))}
c<-lapply(b, extractParms)
fit<-lapply(b, extractGAfit)
exp<-lapply(b, extractExperiment)
d<-unique(c)
r<-list()
cat("length(d)", length(d), "\n")
# construct new list. Keep raw data.
for (i in 1:length(d))
{
cat("d[[", i, "]]\n") 
print(d[[i]])
el<-list()
el$param<-d[[i]]
m<-c %in% d[i]
tmp<-unlist(fit[m])
el$GAfitVec<-tmp
el$GAfit<-mean(tmp)
el$GAstd<-sd(tmp)
el$GAobs<-length(tmp)
el$exp<-Reduce(append, exp[m])
r[[i]]<-el
}

s<-sort(unlist(lapply(r, extractGAfit)), decreasing=TRUE, index.return=TRUE)

result<-r[s$ix]
return(result)
}

#' Convert list of all tried GA solutions into a data frame.
#'
#' @param l  List of all solutions tried generated by 
#'           \code{aggregateP5MetaResults()}.
#'           
#' @return   A data frame with the following columns:
#'           \enumerate{
#'           \item \code{Fit}   Average GA performance of parameters.
#'           \item \code{sigma(Fit)} Standard deviation of \code{Fit}.
#'           \item \code{Obs}   Number of repetitions genetic algorithm
#'                              with a parameter set.
#'           \item \code{popsize} Population size (Meta-GA parameter).
#'           \item \code{generations} Population size (Meta-GA parameter).
#'           \item \code{mutrate} Probability of applying mutation operator.
#'                                  (Meta-GA parameter).
#'           \item \code{bitmutrate} Bit mutation rate.
#'                                  (Meta-GA parameter).
#'           \item \code{crossrate} Probability of applying crossover operator. 
#'                                  (Meta-GA parameter).
#'           } 
#'
#' @export
convertP5MetaResults<-function(l)
{
# extract all fields of the same type.
extractParms<-function(elem)
{  return(elem$param)  }
extractGAfit<-function(elem)
{  return(elem$GAfit)  }
extractGAstd<-function(elem)
{  return(elem$GAstd)  }
extractGAobs<-function(elem)
{  return(elem$GAobs)  }
# data transformations
tmp<-lapply(l, FUN=extractParms)
df1<-t(data.frame(tmp))
fit<-unlist(lapply(l, FUN=extractGAfit))
std<-unlist(lapply(l, FUN=extractGAstd))
obs<-unlist(lapply(l, FUN=extractGAobs))
df2<-data.frame(fit, std, obs)
result<-cbind(df2, df1)
cn<-c("Fit", "sigma(Fit)", "Obs")
cn<-c(cn, "popsize", "generations", "mutrate", "bitmutrate", "crossrate")
row.names(result)<-NULL
names(result)<-cn
return(result)
}

